### ISSUE TITLE
the speed of computation

### ISSUE THREAD

**Issue by HaobinZhou** [daiqile96/OTTERS#1]
Thank you very much for this amazing project that allows us to perform TWAS analysis using summary data. I have set up the code running environment and used it to run GWAS data and eQTLs. However, I noticed that the computation is very slow. For example, there are about 1900 genes that need to be run in Stage I on Chromosome 1, and my computer's CPU is i9-12900H and already running at full capacity, but the computation is still slow. It takes about an hour to compute only 50 genes. I would like to suggest if it is possible to use GPU acceleration to speed up the computation. Of course, I don't know much about GPU acceleration, and this is just my idea. I am looking forward to your reply.

**Comment by daiqile96** [comment]
Thank you for raising this issue! You're correct that computing 50 genes may take up to an hour. In order to accelerate the process, I performed the analysis in parallel by chromosome on a high-performance computing cluster. Additionally, within each chromosome, I conducted the Stage I training simultaneously for 4 genes using the "--thread=4" in training.py. With this setup, I was able to complete the analysis for all chromosomes within 3-4 days using an Intel(R) Xeon(R) Gold 6242 CPU @ 2.80GHz. I requested 6G of memory for each chromosome, and it seems that was sufficient.

Thank you for suggesting the use of a GPU. That would certainly speed up the computing process, and I will consider looking into it and updating the tool in the future.
